### ISSUE TITLE
ImportError: cannot import name _distributor_init

### ISSUE THREAD

**Issue by Mikor-mkr** [MarvinStuede/cmr_lidarloop#1]
Hello!

For starters thank you for taking the time to check my issue. I am looking forward to use your code in my project! I get an Import error as the title says. Specifically the output I get, including the error, when I launch the cmr_lidarloop.launch file is the following:

```
roslaunch cmr_lidarloop cmr_lidarloop.launch 
... logging to /home/antonis/.ros/log/ad4de7ea-b8cd-11eb-8060-d89c67863565/roslaunch-Y530-18176.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Y530:40219/

SUMMARY
========

PARAMETERS
 * /cmr_lidarloop/R_min: 7.5
 * /cmr_lidarloop/R_ms_verify: 5.0
 * /cmr_lidarloop/alpha_thres: 0.5
 * /cmr_lidarloop/beta: 0.0
 * /cmr_lidarloop/i_limit: 0
 * /cmr_lidarloop/leafsize: 0.2
 * /cmr_lidarloop/loop_probability_min: 0.524
 * /cmr_lidarloop/min_inliers: 1000
 * /cmr_lidarloop/n_max_nodes: 200
 * /cmr_lidarloop/n_max_points: 10000
 * /cmr_lidarloop/n_min_points: 7000
 * /cmr_lidarloop/n_ms_start: 3
 * /cmr_lidarloop/n_ms_verify: 3
 * /cmr_lidarloop/n_verify: 3
 * /cmr_lidarloop/odom_topic_name: /rtabmap/odom
 * /cmr_lidarloop/path_clouds: /home/stuede/clouds
 * /cmr_lidarloop/r_limit: 30
 * /cmr_lidarloop/r_max: 50.0
 * /cmr_lidarloop/scan_topic_name: /kitti/velo/point...
 * /cmr_lidarloop/sky_direction: -2
 * /cmr_lidarloop/t_max: 10.0
 * /cmr_lidarloop/throttle_dur: 0.0
 * /cmr_lidarloop/z_limit: 1.0
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /cmr_lidarloop/
    lidar_loopdetection (cmr_lidarloop/lidar_loopdetection)
    lidar_loopdetector_server (cmr_lidarloop/lidar_loopdetector_server.py)
    lidar_registration_server (cmr_lidarloop/lidar_registration_server)

auto-starting new master
process[master]: started with pid [18193]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ad4de7ea-b8cd-11eb-8060-d89c67863565
process[rosout-1]: started with pid [18211]
started core service [/rosout]
process[cmr_lidarloop/lidar_loopdetection-2]: started with pid [18214]
process[cmr_lidarloop/lidar_registration_server-3]: started with pid [18219]
process[cmr_lidarloop/lidar_loopdetector_server-4]: started with pid [18220]
Traceback (most recent call last):
  File "/home/antonis/rtabmap_ws/src/cmr_lidarloop/scripts/lidar_loopdetector_server.py", line 17, in <module>
    import numpy as np
  File "/home/antonis/.local/lib/python2.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
[cmr_lidarloop/lidar_loopdetector_server-4] process has died [pid 18220, exit code 1, cmd /home/antonis/rtabmap_ws/src/cmr_lidarloop/scripts/lidar_loopdetector_server.py __name:=lidar_loopdetector_server __log:=/home/antonis/.ros/log/ad4de7ea-b8cd-11eb-8060-d89c67863565/cmr_lidarloop-lidar_loopdetector_server-4.log].
log file: /home/antonis/.ros/log/ad4de7ea-b8cd-11eb-8060-d89c67863565/cmr_lidarloop-lidar_loopdetector_server-4*.log
[cmr_lidarloop/lidar_loopdetector_server-4] restarting process
```

I understand that it does not import numpy but I do now know what might cause that. Any ideas? Thank you in advance.

**Comment by Mikor-mkr** [comment]
I had multiple numpy versions installed. I did `pip uninstall numpy` according to this [post](https://stackoverflow.com/questions/55048364/numpy-importerror-cannot-import-name-distributor-init) from stackoverflow and now I can use the launch file with no issues so far.
